### ISSUE TITLE
Automate all the things

### ISSUE THREAD

**Issue by ramiroaznar** [ramiroaznar/covid19-geom-by-date#1]
### TODO

- [x] Figure out when the data is going to be updated
- [x] Fix dates as dynamic fields
- [ ] Set up a cronjob to run the scripts
