### ISSUE TITLE
Migrate logic to tinybird

### ISSUE THREAD

**Issue by ramiroaznar** [ramiroaznar/covid19-geom-by-date#10]
### TODO

- [x] Upload datasets to tinybird
- [x] Build import scripts to append new data (append token, encrypted)
- [x] Create pipes with paramenters (read tokens)
