### ISSUE TITLE
Create a master table with geometries

### ISSUE THREAD

**Issue by ramiroaznar** [ramiroaznar/covid19-geom-by-date#7]
### TODO

- [ ] Share two master tables with geometries: polygons and centroids
- [ ] Remove geometries from the main tables
- [ ] Explain how to join both geometries using pandas, geopandas, carto...

**Comment by ramiroaznar** [comment]
Wont fix
